---
title: Seek the Joy
baseurl: "/"
permalink: "/:title/"
layout_style: grid
palette: black
header:
  type: header
  template: header
  title: Seek the Joy
  logo_img: "/images/seek-the-joy.png"
  logo_img_alt: Seek the Joy logo
  has_nav: true
  nav_links:
  - type: action
    template: action
    label: Home
    url: "/"
    style: link
    icon_class: ''
    new_window: false
    no_follow: false
  - type: action
    template: action
    label: About
    url: "/about"
    style: link
    icon_class: ''
    new_window: false
    no_follow: false
  - type: action
    template: action
    label: Style Guide
    url: "/style-guide"
    style: link
    icon_class: ''
    new_window: false
    no_follow: false
  - type: action
    template: action
    label: Contact
    url: "/contact"
    style: link
    icon_class: ''
    new_window: false
    no_follow: false
footer:
  type: footer
  template: footer
  content: "&copy; eric laurits. All rights reserved. "
  has_social: true
  social_links:
  - type: action
    template: action
    label: Twitter
    url: https://twitter.com/ericlaurits
    style: icon
    icon_class: twitter
    new_window: true
    no_follow: false
  - type: action
    template: action
    label: Instagram
    url: https://www.instagram.com/ericlaurits
    style: icon
    icon_class: instagram
    new_window: true
    no_follow: false
  has_subscribe: true
  subscribe_title: Subscribe for new updates
  subscribe_content: Subscribe to my email newsletter to receive useful articles and
    special offers. This monthly email is sent out on the first of every month.
  subscribe_action: "/subscribe-success"
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
domain: https://friendly-turtle-32215.netlify.app
favicon: ''
